development:
 access_key_id: ENV['AWS_ACCESS_KEY']
 secret_access_key: ENV['AWS_SECRET_KEY']
 bucket: ENV['AWS_BUCKET']

staging:
 access_key_id: ENV['AWS_ACCESS_KEY']
 secret_access_key: ENV['AWS_SECRET_KEY']
 bucket: ENV['AWS_BUCKET']

production:
 access_key_id: ENV['AWS_ACCESS_KEY']
 secret_access_key: ENV['AWS_SECRET_KEY']
 bucket: ENV['AWS_BUCKET']